export const propertyStore = [
    {
      id: 1,
      title: "Comfortable Apartment in Palace",
      location:'Sydney',
      featured: true,
      price: 20,
      status:'sale',
      size: 1200,
      bed: 2,
      bath:2,
      img: "../img/1.png",
      info:"Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    },

    {
        id: 2,
        title: "Comfortable Apartment in Palace",
        location:'Sydney',
        featured: true,
        price: 20,
        status:'rent',
        size: 1200,
        bed: 2,
        bath:2,
        img: "../img/2.png",
        info:"Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    },

    {
        id: 3,
        title: "Comfortable Apartment in Palace",
        location:'Sydney',
        featured: false,
        price: 20,
        status:'sale',
        size: 1200,
        bed: 2,
        bath:2,
        img: "../img/3.png",
        info:"Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
      },

    {
        id: 4,
        title: "Comfortable Apartment in Palace",
        location:'Sydney',
        featured: true,
        price: 20,
        status:'rent',
        size: 1200,
        bed: 2,
        bath:2,
        img: "../img/4.png",
        info:"Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    },

    {
        id: 5,
        title: "Comfortable Apartment in Palace",
        location:'Sydney',
        featured: true,
        price: 20,
        status:'rent',
        size: 1200,
        bed: 2,
        bath:2,
        img: "../img/5.png",
        info:"Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    },
    {
        id: 6,
        title: "Comfortable Apartment in Palace",
        location:'Sydney',
        featured: false,
        price: 20,
        status:'rent',
        size: 1200,
        bed: 2,
        bath:2,
        img: "../img/6.png",
        info:"Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    },

];